# Generated by Django 2.0.5 on 2018-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='blog.Tags'),
        ),
    ]
