# Generated by Django 2.0.5 on 2018-05-16 16:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180516_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Article'),
        ),
    ]
